apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "site24x7-labs.fullname" . }}-config
  labels:
    {{- include "site24x7-labs.labels" . | nindent 4 }}
data:
  HTTP_PORT: "{{ .Values.server.httpPort }}"
  GRPC_PORT: "{{ .Values.server.grpcPort }}"
  DB_HOST: {{ if .Values.postgresql.enabled }}{{ include "site24x7-labs.fullname" . }}-postgresql{{ else }}{{ .Values.externalDatabase.host }}{{ end }}
  DB_PORT: {{ if .Values.postgresql.enabled }}"5432"{{ else }}"{{ .Values.externalDatabase.port }}"{{ end }}
  DB_USER: {{ if .Values.postgresql.enabled }}{{ .Values.postgresql.auth.username }}{{ else }}{{ .Values.externalDatabase.user }}{{ end }}
  DB_NAME: {{ if .Values.postgresql.enabled }}{{ .Values.postgresql.auth.database }}{{ else }}{{ .Values.externalDatabase.database }}{{ end }}
  DB_SSLMODE: {{ if .Values.postgresql.enabled }}"disable"{{ else }}"{{ .Values.externalDatabase.sslmode }}"{{ end }}
  REDIS_HOST: {{ if .Values.redis.enabled }}{{ include "site24x7-labs.fullname" . }}-redis-master{{ else }}{{ .Values.externalRedis.host }}{{ end }}
  REDIS_PORT: {{ if .Values.redis.enabled }}"6379"{{ else }}"{{ .Values.externalRedis.port }}"{{ end }}
  JWT_EXPIRY_HOURS: "{{ .Values.auth.jwtExpiryHours }}"
  BCRYPT_COST: "{{ .Values.auth.bcryptCost }}"
  ADMIN_EMAIL: "{{ .Values.auth.adminEmail }}"
  CORS_ORIGIN: "{{ .Values.cors.allowedOrigins }}"
  LOG_LEVEL: "{{ .Values.logging.level }}"
  LOG_FORMAT: "{{ .Values.logging.format }}"
