{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "site24x7-labs.fullname" . }}
  labels:
    {{- include "site24x7-labs.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                {{- if $.Values.frontend.enabled }}
                name: {{ include "site24x7-labs.fullname" $ }}-frontend
                port:
                  name: http
                {{- else }}
                name: {{ include "site24x7-labs.fullname" $ }}-server
                port:
                  name: http
                {{- end }}
          {{- end }}
    {{- end }}
{{- end }}
