apiVersion: v1
kind: Service
metadata:
  name: {{ include "site24x7-labs.fullname" . }}-server
  labels:
    {{- include "site24x7-labs.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "site24x7-labs.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server
